### ISSUE TITLE
main page has not enough puns

### ISSUE THREAD

**Issue by neoncitylights** [MtMNC/mtmnc.github.io#1]
https://mtmnc.github.io/

(thumbs up if you agree)

(also sorry for derping around you can close this if you want xD)

**Comment by MtMNC** [comment]
@SamanthaNguyen I can't seem to replicate the issue. Could you provide step-by-step instructions?

(lol)

**Comment by neoncitylights** [comment]
1.  Open up https://mtmnc.github.io/ in Chrome **instead of Edge/IE 6**  (yes that's the only step shh)

**Comment by MtMNC** [comment]
My only browser is IE 6 though?

**Comment by neoncitylights** [comment]
Renaming the desktop shortcut from "IE 6" to "Google Chrome" should work ;)

**Comment by MtMNC** [comment]
Ah yes there we go.

(Already fixed in https://github.com/MtMNC/mtmnc.github.io/commit/83c9e952f20e8e02ccc1fa9324afeff88e552d0e, closing)
