### ISSUE TITLE
blink vendor prefix in bs01splash/alt/scripts/background.js

### ISSUE THREAD

**Issue by neoncitylights** [MtMNC/mtmnc.github.io#2]
https://github.com/MtMNC/mtmnc.github.io/blob/master/bs01splash/alt/scripts/background.js#L170
https://github.com/MtMNC/mtmnc.github.io/blob/master/bs01splash/alt/scripts/background.js#L109

These should be safe to remove :D

**Comment by MtMNC** [comment]
Thanks for catching those! Removed as of https://github.com/MtMNC/mtmnc.github.io/commit/2bacdf156a09a54d4434baef2ae360ca2e034632.
