### ISSUE TITLE
HTML5 semantics - the sidebar should use the <aside> element

### ISSUE THREAD

**Issue by neoncitylights** [MtMNC/mtmnc.github.io#3]
Offending line: https://github.com/MtMNC/mtmnc.github.io/blob/master/bs01splash/alt/alt.html#L30

Something like this instead: (simplified, you can keep the other attributes stuff but again, this is just a simple concept of what it should like:)

``` html
<aside id="sidebar">
   <nav>
     <ul>...</ul>
     <ul>...</ul>
     <ul>...</ul>
   </nav>
</aside>
```

**Comment by MtMNC** [comment]
Done as of https://github.com/MtMNC/mtmnc.github.io/commit/744f92af8eb99e81038fcc15fa53b2974b65a425. Thanks.
